export const INSUMO_TIPOS = {
  CONCRETO_FC150: 'concreto_fc150',
  CONCRETO_FC200: 'concreto_fc200',
  CONCRETO_FC250: 'concreto_fc250',
  CONCRETO_FC300: 'concreto_fc300',
  CONCRETO_POBRE: 'concreto_pobre',
  MORTERO_1_4: 'mortero_1_4',
  MORTERO_1_5: 'mortero_1_5',
  MORTERO_1_6: 'mortero_1_6',

  ACERO_NO3: 'acero_no3',
  ACERO_NO4: 'acero_no4',
  ACERO_NO5: 'acero_no5',
  ACERO_NO6: 'acero_no6',
  ACERO_NO8: 'acero_no8',
  MALLA_66_1010: 'malla_electrosoldada_6x6_10_10',
  MALLA_44_88: 'malla_electrosoldada_4x4_8_8',
  ALAMBRE_RECOCIDO: 'alambre_recocido',

  CIMBRA_ZAPATAS: 'cimbra_zapatas',
  CIMBRA_MUROS: 'cimbra_muros',
  CIMBRA_COLUMNAS: 'cimbra_columnas',
  CIMBRA_TRABES: 'cimbra_trabes',
  CIMBRA_LOSA: 'cimbra_losa',
  CIMBRA_ESCALERAS: 'cimbra_escaleras',

  EXCAVACION_MANUAL: 'excavacion_manual',
  EXCAVACION_MAQUINA: 'excavacion_maquina',
  PLANTILLA: 'plantilla_concreto_pobre',
  RELLENO_COMPACTADO: 'relleno_compactado',
  ACARREO: 'acarreo_material',

  TABIQUE_14: 'tabique_rojo_14cm',
  TABIQUE_21: 'tabique_rojo_21cm',
  TABIQUE_28: 'tabique_rojo_28cm',
  BLOCK_15: 'block_concreto_15cm',
  BLOCK_20: 'block_concreto_20cm',
  PANEL_COVINTEC: 'panel_covintec',
  PANEL_TABLAROCA: 'panel_tablaroca',

  YESO: 'yeso_blanco',
  MEZCLA_APLANADO: 'mezcla_aplanado',

  PERFIL_IPR: 'perfil_ipr',
  PERFIL_PTR: 'perfil_ptr',
  ANGULO_ESTRUCTURAL: 'angulo_estructural',
  PLACA_ACERO: 'placa_acero',
  SOLDADURA_ELECTRODO: 'soldadura_electrodo',
  PINTURA_ANTICORROSIVA: 'pintura_anticorrosiva',
  PINTURA_ESMALTE: 'pintura_esmalte',

  PERFIL_ALUMINIO: 'perfil_aluminio_kg',
  VIDRIO_6MM: 'vidrio_6mm',
  VIDRIO_LAMINADO: 'vidrio_laminado',
  HULE_NEOPRENO: 'hule_neopreno',
  TORNILLERIA_ALUMINIO: 'tornilleria_aluminio',
  SELLADOR_SILICON: 'sellador_silicon',

  MAMPARA_SANILOCK: 'mampara_sanilock_m2',

  TUBO_REDONDO: 'tubo_redondo_acero',
  TUBO_CUADRADO: 'tubo_cuadrado_acero',
  PLATINA_ACERO: 'platina_acero',

  TUBO_COBRE_12: 'tubo_cobre_12plg',
  TUBO_COBRE_34: 'tubo_cobre_34plg',
  TUBO_PVC_34: 'tubo_pvc_34plg',
  TUBO_PVC_1: 'tubo_pvc_1plg',
  COPLE_COBRE: 'cople_cobre',
  VALVULA_GLOBO: 'valvula_globo',
  TINACO: 'tinaco_rotoplas',

  CABLE_THW_12: 'cable_thw_calibre_12',
  CABLE_THW_10: 'cable_thw_calibre_10',
  CABLE_THW_8: 'cable_thw_calibre_8',
  CONDUIT_EMT_34: 'conduit_emt_34plg',
  CONDUIT_PVC_34: 'conduit_pvc_34plg',
  CAJA_REGISTRO: 'caja_registro_elect',
  CONDULET: 'condulet_elect',
  CINTA_AISLANTE: 'cinta_aislante',

  MO_ALBANIL_PEON: '1A1P',
  MO_FIERRERO: '1F1A',
  MO_HERRERO: '1H1A',
  MO_SOLDADOR: '1S1E',
  MO_CARPINTERO: '1C1A',
  MO_PLOMERO: '1P1E',
  MO_ELECTRICISTA: '1E1E',
  MO_COLOCADOR: '1CO1A',
  MO_ALUMINIERO: '1A1E',
  MO_PEON: '1P',
  MO_AYUDANTE: '1A',
  MO_PINTOR: '1P1A',
  MO_YESERO: '1Y1A',
} as const;

export type InsumoTipoKey = keyof typeof INSUMO_TIPOS;
